# Generated by Django 4.1 on 2023-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='esp32',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
    ]
