# Generated by Django 4.1 on 2023-05-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuariologin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariologin',
            old_name='funcionario',
            new_name='usuario',
        ),
    ]
