# Generated by Django 4.1 on 2023-05-28 17:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariologin',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
