# Generated by Django 4.1 on 2023-05-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_usuariologin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UsuarioLogin',
        ),
    ]
