# Generated by Django 4.1 on 2023-05-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_user_login_id_delete_usuariologin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.rio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
    ]
